const swaggerAutogen = require('swagger-autogen')()


const outputFile = './swagger_output.json'
const endpointsFiles = [  './src/app.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        },
        {
            "name": "Group",
            "description": "Endpoints of Group",

        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    },
    definitions: {
        
        expenditures:{
            "_id": "620f03af4060306a30737a26",
            "money": 101000,
            "note": "tra nợ cho TU",
            "group": "620f63f20f474f81b4fae559",
            "date": "2022-02-18T02:20:42.986Z",
        },
        receipts:{
            "_id": "620f03af4060306a30737a26",
            "money": 10000000,
            "note": "Tien luong thang 2",
            "group": "620f63f20f474f81b4fae559",
            "date": "2022-02-18T02:20:42.986Z",
        },
        Group:  {
                "_id": "620f63f20f474f81b4fae559",
                "name": "tien tieu vat",
                "color": "red",
                "type": "'thu' | 'chi'"
               
        },
        addGroup: {
            $name: "Tiền lương",
            $color: 'ffff',
            $type: "'thu' | 'chi'"
        },
        addPost:{
            "money": 10000000,
            "note": "Tien luong thang 2",
            "group": "620f63f20f474f81b4fae559",
            "date": "2022-02-18T02:20:42.986Z",
            "type": "thu | chi"
        },
        editPost:{
            "money": 10000000,
            "note": "Tien luong thang 2",
            "group": "620f63f20f474f81b4fae559",
        },
        
    }
}


swaggerAutogen(outputFile, endpointsFiles, doc)