const swaggerAutogen = require('swagger-autogen')()


const outputFile = './swagger_output.json'
const endpointsFiles = [  './src/app.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host:  process.env.VIRTUAL_HOST || "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    
    securityDefinitions: {
        Bearer: {
            type: "apiKey",
            in: "header", // can be "header", "query" or "cookie"
            name: "Authorization", // name of the header, query parameter or cookie
            description:
                "Please enter a valid token to test the requests below...",
        },
        
    },
    definitions: {
        
        expenditures:{
            "_id": "620f03af4060306a30737a26",
            "money": 101000,
            "note": "tra nợ cho TU",
            "group": "620f63f20f474f81b4fae559",
            "date": "2022-02-18T02:20:42.986Z",
        },
        receipts:{
            "_id": "620f03af4060306a30737a26",
            "money": 10000000,
            "note": "Tien luong thang 2",
            "group": "620f63f20f474f81b4fae559",
            "date": "2022-02-18T02:20:42.986Z",
        },
        Group:  {
                "_id": "620f63f20f474f81b4fae559",
                "name": "tien tieu vat",
                "color": "red",
                "type": "'thu' | 'chi'"
               
        },
        addGroup: {
            $name: "Tiền lương",
            $color: 'ffff',
            $type: "'thu' | 'chi'"
        },
        addPost:{
            "money": 10000000,
            "note": "Tien luong thang 2",
            "group": "620f63f20f474f81b4fae559",
            "date": "2022-02-18T02:20:42.986Z",
            "type": "thu | chi"
        },
        editPost:{
            "money": 10000000,
            "note": "Tien luong thang 2",
            "group": "620f63f20f474f81b4fae559",
        },
        
    }
}


swaggerAutogen(outputFile, endpointsFiles, doc)